/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 fc.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Fc(props) {
  const { nodes, materials } = useGLTF("./assets/fc.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.fc.geometry}
        material={materials["Steel_-_Satin.002"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./assets/fc.glb");
