/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 mac.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";

export default function Mac(props) {
  const { nodes, materials } = useGLTF("./assets/mac.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.519, 0]} scale={0.103}>
        <mesh
          geometry={nodes.Circle005.geometry}
          material={materials["Frame.003"]}
        />
        <mesh
          geometry={nodes.Circle005_1.geometry}
          material={materials["HeadPhoneHole.001"]}
        />
        <mesh
          geometry={nodes.Circle005_2.geometry}
          material={materials["USB_C_INSIDE.001"]}
        />
        <mesh
          geometry={nodes.Circle005_3.geometry}
          material={materials["TouchbarBorder.001"]}
        />
        <mesh
          geometry={nodes.Circle005_4.geometry}
          material={materials["Keyboard.002"]}
        />
        <group position={[0, -0.509, 0]} scale={5.796}>
          <mesh
            geometry={nodes.Circle007.geometry}
            material={materials["Frame.003"]}
          />
          <mesh
            geometry={nodes.Circle007_1.geometry}
            material={materials["USB_C_INSIDE.001"]}
          />
        </group>
        <group position={[-11.786, -0.15, -8.301]} scale={5.796}>
          <mesh
            geometry={nodes.Circle010.geometry}
            material={materials["Keyboard.003"]}
          />
          <mesh
            geometry={nodes.Circle010_1.geometry}
            material={materials["Key.001"]}
          />
          <mesh
            geometry={nodes.Circle010_2.geometry}
            material={materials["Touchbar.001"]}
          />
        </group>
        <mesh
          geometry={nodes.KeyboardKeyHole.geometry}
          material={materials["Keyboard.003"]}
          position={[-11.786, -0.152, -8.301]}
          scale={5.796}
        />
        <mesh
          geometry={nodes.RubberFoot.geometry}
          material={materials["DarkRubber.001"]}
          position={[-11.951, -0.751, 7.857]}
          scale={5.796}
        />
        <group position={[0.011, -0.211, -10.559]} scale={5.796}>
          <mesh
            geometry={nodes.Circle015.geometry}
            material={materials["HingeBlack.001"]}
          />
          <mesh
            geometry={nodes.Circle015_1.geometry}
            material={materials["HingeMetal.001"]}
          />
        </group>
        <group position={[-15.026, 0.031, 0.604]} scale={5.796}>
          <mesh
            geometry={nodes.Circle016.geometry}
            material={materials["Frame.003"]}
          />
          <mesh
            geometry={nodes.Circle016_1.geometry}
            material={materials["SpeakerHole.001"]}
          />
        </group>
        <group position={[12.204, 0.031, 0.604]} scale={5.796}>
          <mesh
            geometry={nodes.Circle017.geometry}
            material={materials["Frame.003"]}
          />
          <mesh
            geometry={nodes.Circle017_1.geometry}
            material={materials["SpeakerHole.001"]}
          />
        </group>
        <motion.group
          position={[0.01, -0.4, -10.41]}
          dispose={null}
          scale={5.8}
          initial={{ rotateX: 3.15 }}
          animate={{
            rotateX: 1.45,
          }}
          transition={{
            delay: 2,
            duration: 1,
            ease: "linear",
          }}
        >
          <mesh
            geometry={nodes.Circle018.geometry}
            material={materials["Frame.004"]}
          />
          <mesh
            geometry={nodes.Circle018_1.geometry}
            material={materials["Screen.001"]}
          />
          <mesh
            geometry={nodes.Circle018_2.geometry}
            material={materials["ScreenGlass.001"]}
          />
          <mesh
            geometry={nodes.Circle018_3.geometry}
            material={materials["Rubber.001"]}
          />
          <mesh
            geometry={nodes.Circle018_4.geometry}
            material={materials["DisplayGlass.001"]}
          />
          <mesh
            geometry={nodes.AppleLogo000.geometry}
            material={materials["AppleLogo.001"]}
            position={[0.005, -0.151, -1.795]}
            scale={0.579}
          />
        </motion.group>
      </group>
    </group>
  );
}

useGLTF.preload("./assets/mac.glb");
