/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 uc.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Uc(props) {
  const { nodes, materials } = useGLTF('./assets/uc.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.uc.geometry} material={materials['Steel_-_Satin.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./assets/uc.glb')
