const projects = [
  {
    title: "AlgoSim",
    sourceLink: "https://github.com/dan10ish/AlgoSim",
    projectLink: null,
    tags: ["algorithm"],
    status: "offline",
    video: "algosim.mp4",
  },
  {
    title: "CogniCart",
    sourceLink: "https://github.com/dan10ish/cogni-cart",
    projectLink: null,
    tags: ["ml"],
    status: "offline",
    video: "cognicart.mp4",
  },
  {
    title: "Code",
    sourceLink: "https://github.com/dan10ish/code",
    projectLink: "http://dan10ish.github.io/code",
    tags: ["web"],
    status: "live",
    video: "code.mp4",
  },
  {
    title: "3DOF Robotic Arm",
    sourceLink: "https://github.com/dan10ish/3DOF-RoboticArm-C",
    projectLink: null,
    tags: ["robotics"],
    status: "offline",
    video: "3dof.mp4",
  },
  {
    title: "Pathfinder",
    sourceLink: "https://github.com/dan10ish/pathfinding-visualizer",
    projectLink: "https://dan10ish.github.io/pathfinding-visualizer/",
    tags: ["algorithm"],
    status: "live",
    video: "path.mp4",
  },
  {
    title: "macOS Portfolio",
    sourceLink: "https://github.com/dan10ish/os",
    projectLink: "https://os-danishs-projects-31d8c677.vercel.app/",
    tags: ["web"],
    status: "live",
    video: "mac.mp4",
  },
  {
    title: "Arm Visualizer",
    sourceLink: "https://github.com/dan10ish/RoboticArm",
    projectLink: "https://dan10ish.github.io/RoboticArm/",
    tags: ["robotics"],
    status: "live",
    video: "rob-visual.mp4",
  },
  {
    title: "College Notes",
    sourceLink: "https://github.com/dan10ish/college",
    projectLink: "https://dan10ish.github.io/college/",
    tags: ["college"],
    status: "live",
    video: "notes.mp4",
  },
  {
    title: "Comment Toxicity",
    sourceLink: "https://github.com/dan10ish/CommentToxicity",
    projectLink: null,
    tags: ["ml"],
    status: "offline",
    video: null,
  },
  {
    title: "Terminal Hacker",
    sourceLink: "https://github.com/dan10ish/Unity-Terminal_Hacker",
    projectLink: null,
    tags: ["game"],
    status: "offline",
    video: "terminal.mp4",
  },
  {
    title: "Office",
    sourceLink: "https://github.com/dan10ish/Office",
    projectLink: "https://dan10ish.github.io/Office/",
    tags: ["game"],
    status: "live",
    video: "office.mp4",
  },
  {
    title: "Cube Runner",
    sourceLink: "https://github.com/dan10ish/Unity-ProjectRun",
    projectLink: null,
    tags: ["game"],
    status: "offline",
    video: "cube.mp4",
  },
  {
    title: "Galaxy",
    sourceLink: "https://github.com/dan10ish/Galaxy",
    projectLink: "https://dan10ish.github.io/Galaxy/",
    tags: ["web"],
    status: "live",
    video: "galaxy.mp4",
  },
  {
    title: "Personal Website",
    sourceLink: "https://github.com/dan10ish/dan10ish.github.io",
    projectLink: "https://dan10ish.github.io",
    tags: ["web"],
    status: "live",
    video: "web.mp4",
  },
];

export function getProjects() {
  return projects;
}
