const projects = [
  {
    title: "Cold Mail Bot",
    description:
      "Drop a job post URL + your resume, get a tailored cold email using generative AI.",
    sourceLink: "https://github.com/dan10ish/coldmailbot",
    projectLink: "https://mailbot.streamlit.app",
    tags: ["ml"],
    home: true,
    video: "cold.mp4",
    // highlight: true,
  },
  {
    title: "Code",
    description: "Code Python, C++, JavaScript & p5.js with no setup.",
    sourceLink: "https://github.com/dan10ish/code",
    projectLink: "http://dan10ish.github.io/code",
    tags: ["web"],
    home: true,
    video: "code.mp4",
  },
  {
    title: "3DOF Robotic Arm",
    description: "Math modelling of a yaw-pitch-pitch 3DOF robotic arm in C",
    sourceLink: "https://github.com/dan10ish/3DOF-RoboticArm-C",
    projectLink: null,
    tags: ["rbtx"],
    home: true,
    video: "3dof.mp4",
  },
  {
    title: "Pathfinder",
    description: "Visualize Dijkstra, A*, BFS & DFS on random generated mazes",
    sourceLink: "https://github.com/dan10ish/pathfinding-visualizer",
    projectLink: "https://dan10ish.github.io/pathfinding-visualizer/",
    tags: ["web"],
    home: true,
    video: "path.mp4",
  },
  {
    title: "macOS Portfolio",
    description: "Personal website showcased in a macOS-style UI interface",
    sourceLink: "https://github.com/dan10ish/os",
    projectLink: "https://os.danish.bio",
    tags: ["web"],
    home: true,
    video: "mac.mp4",
  },
  {
    title: "Arm Visualizer",
    description:
      "3DOF robotic arm visualization using r3f, drei & framer-motion",
    sourceLink: "https://github.com/dan10ish/RoboticArm",
    projectLink: "https://dan10ish.github.io/RoboticArm/",
    tags: ["rbtx"],
    home: true,
    video: "rob-visual.mp4",
  },
  {
    title: "College Notes",
    description: "Library-style UI for my mechatronics engineering handwritten notes",
    sourceLink: "https://github.com/dan10ish/college",
    projectLink: "https://danish.bio/college/",
    tags: ["notes"],
    home: true,
    video: "notes.mp4",
  },
  {
    title: "Comment Toxicity",
    description: "Toxicity detection algorithm developed using deep learning",
    sourceLink: "https://github.com/dan10ish/CommentToxicity",
    projectLink: null,
    tags: ["ml"],
    home: false,
    video: null,
  },
  {
    title: "Office",
    description: "3D website using r3f, framer-motion & Blender",
    sourceLink: "https://github.com/dan10ish/Office",
    projectLink: "https://dan10ish.github.io/Office/",
    tags: ["3d"],
    home: false,
    video: "office.mp4",
  },
  {
    title: "Galaxy",
    description: "3D particle animation using r3f",
    sourceLink: "https://github.com/dan10ish/Galaxy",
    projectLink: "https://dan10ish.github.io/Galaxy/",
    tags: ["3d"],
    home: false,
    video: "galaxy.mp4",
  },
  {
    title: "Terminal Hacker",
    description: "Text-based terminal game to guess anagram-hinted passwords.",
    sourceLink: "https://github.com/dan10ish/Unity-Terminal_Hacker",
    projectLink: null,
    tags: ["game"],
    home: false,
    video: null,
  },
  {
    title: "Personal Website",
    description: "This website with project showcase and blog functionality",
    sourceLink: "https://github.com/dan10ish/dan10ish.github.io",
    projectLink: "https://dan10ish.github.io",
    tags: ["web"],
    home: false,
    video: "web.mp4",
  },
  {
    title: "Cube Runner",
    description: "A 3D obstacle avoiding game with difficulty levels.",
    sourceLink: "https://github.com/dan10ish/Unity-ProjectRun",
    projectLink: null,
    tags: ["game"],
    home: false,
    video: null,
  },
];

export function getProjects() {
  return projects;
}
